### ISSUE TITLE
images for gh-pages

### ISSUE THREAD

**Issue by jonpinhorn** [jonpinhorn/shrikhand#11]
![sg_1200](https://cloud.githubusercontent.com/assets/8477580/11318394/8113a1dc-9048-11e5-97dd-a0582a9504fc.jpg)
![shrikhandsale](https://cloud.githubusercontent.com/assets/8477580/11318393/8110d1dc-9048-11e5-8d07-63b01791b7ea.png)
![shrikhandwalls_1](https://cloud.githubusercontent.com/assets/8477580/11535579/5fe3644e-990c-11e5-8abe-d7fcaa3a3584.png)
![shrikhandwalls_2](https://cloud.githubusercontent.com/assets/8477580/11535580/61f99122-990c-11e5-962e-805686486ee9.png)
![shrikhandwalls_3](https://cloud.githubusercontent.com/assets/8477580/11562299/18716890-99c5-11e5-9397-fd320cfc9d50.png)
![shrikhandwalls_4](https://cloud.githubusercontent.com/assets/8477580/11562378/8eb851ee-99c5-11e5-9279-b69d73b08ad7.png)

**Comment by davelab6** [comment]
Love it

**Comment by davelab6** [comment]
I'm confused by this issue; the source files to the images, nor the images, are in the repo... it seems your gh-pages html is linking to them here..? :)

**Comment by jonpinhorn** [comment]
If you’re confused what chance to I stand. I don’t even understand what you’re saying.

**Comment by davelab6** [comment]
In https://github.com/jonpinhorn/shrikhand/blob/gh-pages/index.html#L9 the image's src is to the images as uploaded into this issue; the images are not checked into the repo. 

So, please check the images into the repo with the PSD/etc source files

**Comment by jonpinhorn** [comment]
I thought the purpose of having the images in an issue was so that it didn’t need to be loaded into the repo? That said it’s no problem for me to do so.

Also, I don’t see how this affects the repo conflict I’m having which is stopping me updating Liang’s compilation work? That’s what I need your help with.

Thanks.

JP
